# We are going to do the sentimental analysis of YouTube comments of Blackadam's Trailer.


In [2]:
# Data source - Kaggle

In [52]:
#Libraries 
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
%matplotlib inline
import os

# Import functions for data preprocessing & data preparation
from sklearn.preprocessing import LabelEncoder
from sklearn.utils import resample
from sklearn.feature_extraction.text import CountVectorizer
from nltk.sentiment.vader import SentimentIntensityAnalyzer

from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.stem import PorterStemmer, LancasterStemmer
from nltk.stem.snowball import SnowballStemmer
from nltk.corpus import stopwords
from nltk.corpus import wordnet
import string
from string import punctuation
import nltk
import re

# Reading data

In [53]:
data = pd.read_csv('/Users/sanskarsmacbook/Downloads/comments.csv')
data.columns


Index(['Unnamed: 0', 'Comment', 'Likes', 'Time', 'user', 'UserLink'], dtype='object')

In [54]:
data1=data.drop(['Unnamed: 0','Likes','Time','user','UserLink'],axis=1)
data1

Comment
0    Love how Dr. Fate's design looks and how cool ...
1    I can’t get over how good everything looks. Dr...
2    Really hoping that this can save DC's movie un...
3    U cant deny how good this looks.Now if they ca...
4    From this trailer, I have a feeling that this ...
..                                                 ...
275  I want to see this. It may be one of his most ...
276       wow thats very amazing. I can't wait to see.
277                    Doctor Fate is why i'm watching
278  This looks fire. DC looks like they stepping t...
279  Shazam : "I don't want fight you Black Adam."B...

[280 rows x 1 columns]

# Data labeling

In [55]:
nltk.download('vader_lexicon')
sentiments = SentimentIntensityAnalyzer()
data1["Positive"] = [sentiments.polarity_scores(i)["pos"] for i in data1["Comment"]]
data1["Negative"] = [sentiments.polarity_scores(i)["neg"] for i in data1["Comment"]]
data1["Neutral"] = [sentiments.polarity_scores(i)["neu"] for i in data1["Comment"]]
data1['Compound'] = [sentiments.polarity_scores(i)["compound"] for i in data1["Comment"]]
score = data1["Compound"].values
sentiment = []
for i in score:
    if i >= 0.05 :
        sentiment.append('Positive')
    elif i <= -0.05 :
        sentiment.append('Negative')
    else:
        sentiment.append('Neutral')
data1["Sentiment"] = sentiment
data1.head()

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /Users/sanskarsmacbook/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!


Comment  Positive  Negative  \
0  Love how Dr. Fate's design looks and how cool ...     0.384     0.000   
1  I can’t get over how good everything looks. Dr...     0.153     0.000   
2  Really hoping that this can save DC's movie un...     0.375     0.000   
3  U cant deny how good this looks.Now if they ca...     0.302     0.049   
4  From this trailer, I have a feeling that this ...     0.131     0.000   

   Neutral  Compound Sentiment  
0    0.616    0.8910  Positive  
1    0.847    0.6801  Positive  
2    0.625    0.9216  Positive  
3    0.649    0.9262  Positive  
4    0.869    0.4416  Positive

# Final data

In [56]:
data2=data1.drop(['Positive','Negative','Neutral','Compound'],axis=1)
data2.head()

Comment Sentiment
0  Love how Dr. Fate's design looks and how cool ...  Positive
1  I can’t get over how good everything looks. Dr...  Positive
2  Really hoping that this can save DC's movie un...  Positive
3  U cant deny how good this looks.Now if they ca...  Positive
4  From this trailer, I have a feeling that this ...  Positive

# Data Transformation

In [57]:
nltk.download('stopwords')
stop_words = stopwords.words('english')
porter_stemmer = PorterStemmer()
lancaster_stemmer = LancasterStemmer() 
snowball_stemer = SnowballStemmer(language="english")
lzr = WordNetLemmatizer()

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/sanskarsmacbook/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [58]:
def text_processing(text):   
    # convert text into lowercase
    text = text.lower()

    # remove new line characters in text
    text = re.sub(r'\n',' ', text)
    
    # remove punctuations from text
    text = re.sub('[%s]' % re.escape(punctuation), "", text)
    
    # remove references and hashtags from text
    text = re.sub("^a-zA-Z0-9$,.", "", text)
    
    # remove multiple spaces from text
    text = re.sub(r'\s+', ' ', text, flags=re.I)
    
    # remove special characters from text
    text = re.sub(r'\W', ' ', text)

    text = ' '.join([word for word in word_tokenize(text) if word not in stop_words])
    
    # stemming using porter stemmer from nltk package - msh a7sn 7aga - momken: lancaster, snowball
    # text=' '.join([porter_stemmer.stem(word) for word in word_tokenize(text)])
    # text=' '.join([lancaster_stemmer.stem(word) for word in word_tokenize(text)])
    # text=' '.join([snowball_stemer.stem(word) for word in word_tokenize(text)])
    
    # lemmatizer using WordNetLemmatizer from nltk package
    text=' '.join([lzr.lemmatize(word) for word in word_tokenize(text)])

    return text

In [59]:
nltk.download('omw-1.4')
nltk.download('wordnet')
data_copy = data2.copy()
data_copy.Comment = data_copy.Comment.apply(lambda text: text_processing(text))

[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /Users/sanskarsmacbook/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/sanskarsmacbook/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [60]:
le = LabelEncoder()
data_copy['Sentiment'] = le.fit_transform(data_copy['Sentiment'])


In [61]:
processed_data = {
    'Sentence':data_copy.Comment,
    'Sentiment':data_copy['Sentiment']
}

processed_data = pd.DataFrame(processed_data)
processed_data.head()

Sentence  Sentiment
0  love dr fate design look cool scene look power...          2
1  get good everything look dr fate magic cyclone...          2
2  really hoping save dc movie universe looking n...          2
3  u cant deny good looksnow follow rest movie go...          2
4  trailer feeling movie going one movie would ne...          2

In [67]:
processed_data['Sentiment'].value_counts()

2    205
1     39
0     36
Name: Sentiment, dtype: int64

# Balancing Data 

In [63]:


df_neutral = processed_data[(processed_data['Sentiment']==1)] 
df_negative = processed_data[(processed_data['Sentiment']==0)]
df_positive = processed_data[(processed_data['Sentiment']==2)]

# upsample minority classes
df_negative_upsampled = resample(df_negative, 
                                 replace=True,    
                                 n_samples= 205, 
                                 random_state=42)  

df_neutral_upsampled = resample(df_neutral, 
                                 replace=True,    
                                 n_samples= 205, 
                                 random_state=42)  


# Concatenate the upsampled dataframes with the neutral dataframe
final_data = pd.concat([df_negative_upsampled,df_neutral_upsampled,df_positive])

In [64]:
final_data['Sentiment'].value_counts()

0    205
1    205
2    205
Name: Sentiment, dtype: int64

In [65]:
corpus = []
for sentence in final_data['Sentence']:
    corpus.append(sentence)
corpus[0:5]


['trailer look sick im definitely watching movie',
 'actually look like villain trailer',
 'movie going push dc top comic book movie disaster early dceu new msheu mess two awesome projekts behind suicide squad peacemaker yeah going rock pun kinda intended',
 'damn sure im gon na watchdc seems going right track',
 'okay look absolutely incredible dc making look foolish ever even skeptical film definitely seeing opening weekend']

In [66]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=1500)
X = cv.fit_transform(corpus).toarray()
y = final_data.iloc[:, -1].values

# Machine learning model

In [26]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

# Evaluation

In [31]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
cm

array([[58,  0,  0],
       [ 0, 70,  0],
       [11,  1, 45]])

In [32]:
nb_score = accuracy_score(y_test, y_pred)
print('accuracy',nb_score)

accuracy 0.9351351351351351


# Random Forest classifier

In [42]:
from sklearn.ensemble import RandomForestClassifier

# ... (your preprocessing code) ...

# Initialize the Random Forest classifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=0)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

# Train the Random Forest classifier on the training data
rf_classifier.fit(X_train, y_train)

# Make predictions on the test data
y_pred_rf = rf_classifier.predict(X_test)

# Calculate the confusion matrix and accuracy score
cm_rf = confusion_matrix(y_test, y_pred_rf)
accuracy_rf = accuracy_score(y_test, y_pred_rf)

print("Confusion Matrix (Random Forest):\n", cm_rf)
print("Accuracy (Random Forest):", accuracy_rf)


Confusion Matrix (Random Forest):
 [[55  3  0]
 [ 0 69  1]
 [ 1 10 46]]
Accuracy (Random Forest): 0.918918918918919


# Logistic Regression classifier

In [47]:
from sklearn.linear_model import LogisticRegression

# ... (your preprocessing code) ...

# Initialize the Logistic Regression classifier
logreg_classifier = LogisticRegression(max_iter=1000, random_state=0)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

# Train the Logistic Regression classifier on the training data
logreg_classifier.fit(X_train, y_train)

# Make predictions on the test data
y_pred_logreg = logreg_classifier.predict(X_test)

# Calculate the confusion matrix and accuracy score
cm_logreg = confusion_matrix(y_test, y_pred_logreg)
accuracy_logreg = accuracy_score(y_test, y_pred_logreg)

print("Confusion Matrix (Logistic Regression):\n", cm_logreg)
print("Accuracy (Logistic Regression):", accuracy_logreg)


Confusion Matrix (Logistic Regression):
 [[55  3  0]
 [ 1 69  0]
 [ 2  8 47]]
Accuracy (Logistic Regression): 0.9243243243243243


# SVM classifier

In [48]:
from sklearn.svm import SVC

# ... (your preprocessing code) ...

# Initialize the SVM classifier
svm_classifier = SVC(kernel='linear', random_state=0)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

# Train the SVM classifier on the training data
svm_classifier.fit(X_train, y_train)

# Make predictions on the test data
y_pred_svm = svm_classifier.predict(X_test)

# Calculate the confusion matrix and accuracy score
cm_svm = confusion_matrix(y_test, y_pred_svm)
accuracy_svm = accuracy_score(y_test, y_pred_svm)

print("Confusion Matrix (SVM):\n", cm_svm)
print("Accuracy (SVM):", accuracy_svm)



Confusion Matrix (SVM):
 [[55  3  0]
 [ 0 70  0]
 [ 2  7 48]]
Accuracy (SVM): 0.9351351351351351
